#!/usr/bin/env bash
# This script shows loops from 1-10 as per requirement

iterator=1

while (( iterator <= 10 ))
do
    if [ "$iterator" -eq "4" ]
    then
        echo "bad luck"
    elif [ "$iterator" -eq "8" ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi

    iterator=$(( iterator + 1 ))
done
