#!/usr/bin/env bash
# The time for 12 hours and 59 minutes is displayed in this script

hour=0

while [ "$hour" -le "12" ]
do
    echo "Hour: $hour"
    minute=1

    while [ "$minute" -le "59" ]
    do
        echo "$minute"
        minute=$(( minute + 1 ))
    done

    hour=$(( hour + 1 ))
done
