#!/usr/bin/env bash
# Information about the school file is in this script as per requirement

file="school"
if [ -e "$file" ]
then
    echo "school file exists"
    if [ ! -s "$file" ] # space needed after not(!)
    then
        echo "school file is empty"
    fi
    if [ -s "$file" ]   # if file size is non-zero thens check is true 
    then
        echo "school file is not empty"
    fi
    if [ -f "$file" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
